### ISSUE TITLE
How to get hex tile coordinates?

### ISSUE THREAD

**Issue by sergeiwallace** [Mekire/hex3d#1]
I'd like to implement mouseover higlighting and/or text box with this hex3d map, but I'm not sure how to get an individual hex tile's coordinates. Could you help me out with understanding the code?

**Comment by Mekire** [comment]
I added mouseover in an early version if you haven't seen that:  
https://github.com/Mekire/hex_pygame_redit  
If you take a look at that, the same idea would work here.
Add a mask to the tiles for their top piece and do point mask collision with the mouse.  If you are doing a lot of rotation though you will have to recalculate the mask every time. 

This program was more just an example of what could be done rather than something that can easily be used.  You are going to need to do some work to incorporate it into another program successfully.
